### ISSUE TITLE
apiInstance.update api error

### ISSUE THREAD

**Issue by yuexiajiayan** [manticoresoftware/manticoresearch-java#17]
sdk version 3.3.0
Manticore 6.2.12 dc5144d35@230822 (columnar 2.2.4 5aec342@230822) (secondary 2.2.4 5aec342@230822)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2023, Manticore Software LTD (https://manticoresearch.com)

 
Exception in thread "main" javax.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:900)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:845)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101)
	at com.manticoresearch.client.ApiClient.deserialize(ApiClient.java:1039)
	at com.manticoresearch.client.ApiClient.invokeAPI(ApiClient.java:1224)
	at com.manticoresearch.client.api.IndexApi.updateWithHttpInfo(IndexApi.java:292)
	at com.manticoresearch.client.api.IndexApi.update(IndexApi.java:264)
	at com.lilin.imcccallcenter.Test1.main(Test1.java:90)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.manticoresearch.client.model.UpdateResponse` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1322)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:640)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:221)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2007)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1174)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:837)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
	... 14 more

Process finished with exit code 1

**Comment by sanikolaev** [comment]
Hi. How can this be reproduced?

**Comment by yuexiajiayan** [comment]
![image](https://github.com/manticoresoftware/manticoresearch-java/assets/16077858/b67023a2-574b-4d1a-b100-18b6ba7cfa21)

width code:
 UpdateDocumentRequest r =new UpdateDocumentRequest();
            r.setIndex("test");
            r.setId(8216866655737741317L);
            r.setDoc(new HashMap<String,Object >(){{
                put("title","ces1");
                put("a","ces1");
            }} );
            try {
                new IndexApi(defaultClient).update( r );
            } catch (ApiException e) {
                e.printStackTrace();
            }

**Comment by Nick-S-2018** [comment]
It's fixed in the latest release: https://github.com/manticoresoftware/manticoresearch-java/releases/tag/3.3.1
