### ISSUE TITLE
Unable to use SearchAPI with spring boot application

### ISSUE THREAD

**Issue by ayaankhan98** [manticoresoftware/manticoresearch-java#18]
I have a sample code shown below
```
package com.example.test;

import com.manticoresearch.client.ApiClient;
import com.manticoresearch.client.ApiException;
import com.manticoresearch.client.Configuration;
import com.manticoresearch.client.model.*;
import com.manticoresearch.client.api.SearchApi;

public class TestApplication {

    public static void main(String[] args) {
        ApiClient client = Configuration.getDefaultApiClient();
        client.setBasePath("http://127.0.0.1:9308");
        SearchApi searchApi = new SearchApi(client);
        try {
            // Create SearchRequest
            SearchRequest searchRequest = new SearchRequest();
            searchRequest.setIndex("test");
            QueryFilter queryFilter = new QueryFilter();
            queryFilter.setQueryString("");
            searchRequest.setFulltextFilter(queryFilter);

            // Perform a search
            SearchResponse searchResponse = searchApi.search(searchRequest);
            System.out.println( searchResponse.toString() );
        } catch (ApiException e) {
            System.err.println("Exception when calling SearchApi#search");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
        }
    }
}

```

I have added dependency in my `pom.xml`

```
        <dependency>
            <groupId>com.manticoresearch</groupId>
            <artifactId>manticoresearch</artifactId>
            <version>4.0.0</version>
            <scope>compile</scope>
        </dependency>
```

When I try to run, it throws the following errors.

```
/usr/lib/jvm/java-21-jdk/bin/java -javaagent:/opt/intellij-idea-ultimate-edition/lib/idea_rt.jar=41553:/opt/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /home/ayaankhan/workspace/repos/test/target/classes:/home/ayaankhan/.m2/repository/org/springframework/boot/spring-boot-starter/3.2.0/spring-boot-starter-3.2.0.jar:/home/ayaankhan/.m2/repository/org/springframework/boot/spring-boot/3.2.0/spring-boot-3.2.0.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-context/6.1.1/spring-context-6.1.1.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-aop/6.1.1/spring-aop-6.1.1.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-beans/6.1.1/spring-beans-6.1.1.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-expression/6.1.1/spring-expression-6.1.1.jar:/home/ayaankhan/.m2/repository/io/micrometer/micrometer-observation/1.12.0/micrometer-observation-1.12.0.jar:/home/ayaankhan/.m2/repository/io/micrometer/micrometer-commons/1.12.0/micrometer-commons-1.12.0.jar:/home/ayaankhan/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.2.0/spring-boot-autoconfigure-3.2.0.jar:/home/ayaankhan/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.2.0/spring-boot-starter-logging-3.2.0.jar:/home/ayaankhan/.m2/repository/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar:/home/ayaankhan/.m2/repository/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar:/home/ayaankhan/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.21.1/log4j-to-slf4j-2.21.1.jar:/home/ayaankhan/.m2/repository/org/apache/logging/log4j/log4j-api/2.21.1/log4j-api-2.21.1.jar:/home/ayaankhan/.m2/repository/org/slf4j/jul-to-slf4j/2.0.9/jul-to-slf4j-2.0.9.jar:/home/ayaankhan/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-core/6.1.1/spring-core-6.1.1.jar:/home/ayaankhan/.m2/repository/org/springframework/spring-jcl/6.1.1/spring-jcl-6.1.1.jar:/home/ayaankhan/.m2/repository/org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar:/home/ayaankhan/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/home/ayaankhan/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.1/jakarta.xml.bind-api-4.0.1.jar:/home/ayaankhan/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.2/jakarta.activation-api-2.1.2.jar:/home/ayaankhan/.m2/repository/com/manticoresearch/manticoresearch/4.0.0/manticoresearch-4.0.0.jar:/home/ayaankhan/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/core/jersey-client/3.1.3/jersey-client-3.1.3.jar:/home/ayaankhan/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/3.1.0/jakarta.ws.rs-api-3.1.0.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/core/jersey-common/3.1.3/jersey-common-3.1.3.jar:/home/ayaankhan/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.jar:/home/ayaankhan/.m2/repository/jakarta/inject/jakarta.inject-api/2.0.1/jakarta.inject-api-2.0.1.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/3.1.3/jersey-hk2-3.1.3.jar:/home/ayaankhan/.m2/repository/org/glassfish/hk2/hk2-locator/3.0.4/hk2-locator-3.0.4.jar:/home/ayaankhan/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/3.0.4/aopalliance-repackaged-3.0.4.jar:/home/ayaankhan/.m2/repository/org/glassfish/hk2/hk2-api/3.0.4/hk2-api-3.0.4.jar:/home/ayaankhan/.m2/repository/org/glassfish/hk2/hk2-utils/3.0.4/hk2-utils-3.0.4.jar:/home/ayaankhan/.m2/repository/org/javassist/javassist/3.29.2-GA/javassist-3.29.2-GA.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/media/jersey-media-multipart/3.1.3/jersey-media-multipart-3.1.3.jar:/home/ayaankhan/.m2/repository/org/jvnet/mimepull/mimepull/1.9.15/mimepull-1.9.15.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/3.1.3/jersey-media-json-jackson-3.1.3.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/ext/jersey-entity-filtering/3.1.3/jersey-entity-filtering-3.1.3.jar:/home/ayaankhan/.m2/repository/com/fasterxml/jackson/module/jackson-module-jakarta-xmlbind-annotations/2.15.3/jackson-module-jakarta-xmlbind-annotations-2.15.3.jar:/home/ayaankhan/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.3/jackson-core-2.15.3.jar:/home/ayaankhan/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.3/jackson-annotations-2.15.3.jar:/home/ayaankhan/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.3/jackson-databind-2.15.3.jar:/home/ayaankhan/.m2/repository/org/openapitools/jackson-databind-nullable/0.2.6/jackson-databind-nullable-0.2.6.jar:/home/ayaankhan/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.15.3/jackson-datatype-jsr310-2.15.3.jar:/home/ayaankhan/.m2/repository/org/glassfish/jersey/connectors/jersey-apache-connector/3.1.3/jersey-apache-connector-3.1.3.jar:/home/ayaankhan/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar:/home/ayaankhan/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/home/ayaankhan/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/ayaankhan/.m2/repository/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar com.example.test.TestApplication
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
	at com.manticoresearch.client.Configuration.<clinit>(Configuration.java:18)
	at com.example.test.TestApplication.main(TestApplication.java:12)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 2 more
```

**Comment by ayaankhan98** [comment]
@sanikolaev

**Comment by sanikolaev** [comment]
Thank you for the 5th open issue about Spring boot :)

**Comment by Nick-S-2018** [comment]
It works now with our new release https://github.com/manticoresoftware/manticoresearch-java/releases/tag/5.0.0
