### ISSUE TITLE
bulk insert error

### ISSUE THREAD

**Issue by LPeng111** [manticoresoftware/manticoresearch-java#22]
here is my code:

```
import com.manticoresearch.client.ApiClient;  
import com.manticoresearch.client.ApiException;  
import com.manticoresearch.client.Configuration;  
import com.manticoresearch.client.api.IndexApi;  
import com.manticoresearch.client.api.SearchApi;  
import com.manticoresearch.client.model.BulkResponse;  
import com.manticoresearch.client.model.QueryFilter;  
import com.manticoresearch.client.model.SearchRequest;  
import com.manticoresearch.client.model.SearchResponse;  
  
public class ApiExample {  
  
    public static void main(String[] args) {  
        ApiClient defaultClient = Configuration.getDefaultApiClient();  
        defaultClient.setBasePath("http://127.0.0.1:9308");  
  
        IndexApi apiInstance = new IndexApi(defaultClient);  
        // String  
        String body = "'{\"insert\": {\"index\": \"test\", \"id\": 1, \"doc\": {\"title\": \"Title 1\"}}},\n{\"insert\": {\"index\": \"test\", \"id\": 2, \"doc\": {\"title\": \"Title 2\"}}}'"; //  
        try {  
            BulkResponse result = apiInstance.bulk(body);  
            System.out.println(result);  
        } catch (ApiException e) {  
            System.err.println("Exception when calling IndexApi#bulk");  
            System.err.println("Status code: "   e.getCode());  
            System.err.println("Reason: "   e.getResponseBody());  
            System.err.println("Response headers: "   e.getResponseHeaders());  
            e.printStackTrace();  
        }  
    }  
} 
```

the exception is ``` com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.manticoresearch.client.model.BulkResponse` from Array value (token `JsonToken.START_ARRAY`)```

please help me, thanks

**Comment by Nick-S-2018** [comment]
Hi,
A piece of code in Readme you probably used as an example was incorrect so we've fixed it:  https://github.com/manticoresoftware/manticoresearch-java/blob/master/README.md

**Comment by LPeng111** [comment]
Hello, I updated the code according to the new example and still got the same error。
`Exception in thread "main" jakarta.ws.rs.ProcessingException: Error reading entity from input stream.
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:903)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:848)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:340)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:104)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:101)
	at com.manticoresearch.client.ApiClient.deserialize(ApiClient.java:1048)
	at com.manticoresearch.client.ApiClient.invokeAPI(ApiClient.java:1233)
	at com.manticoresearch.client.api.IndexApi.bulkWithHttpInfo(IndexApi.java:100)
	at com.manticoresearch.client.api.IndexApi.bulk(IndexApi.java:72)
	at com.singhand.manticoresearch.TestMain.main(TestMain.java:28)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.manticoresearch.client.model.BulkResponse` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:650)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2079)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1229)
	at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:831)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:888)
	... 14 more`

I also tried using an HTTP request, which returned something like this.
![image](https://github.com/user-attachments/assets/54131b2a-15e8-4d35-a62d-f4fa250bb13b)

**Comment by Nick-S-2018** [comment]
Hi,
Have you added the required `-H "Content-Type: application/x-ndjson"` header to your HTTP bulk request? https://manual.manticoresearch.com/dev/Data_creation_and_modification/Adding_documents_to_a_table/Adding_documents_to_a_real-time_table?client=JSON#Bulk-adding-documents

Also, before trying the example code please check that the `test` table doesn't exist already. If so, delete it first and then run the code.

**Comment by LPeng111** [comment]
Hi,
1.I added the request header
![image](https://github.com/user-attachments/assets/2d40fc8f-babb-470c-8440-3334d6f02646)
2.I'm sure the table doesn't exist.

**Comment by Nick-S-2018** [comment]
Maybe, my previous comment was a bit confusing.  So, in the first case , when you try a pure HTTP request, the table you address, `bid_data_test`, must exist already. Does it?

In the second case, when you reproduce the example form Readme, the table must not exist at the beginning.  You create it with ` utilsApi.sql("CREATE TABLE IF NOT EXISTS test (title text)", true);`, then execute a bulk request, but still get an error. Right?

**Comment by LPeng111** [comment]
Hi, I've verified both. It returns the same result whether the table exists or not.

**Comment by Nick-S-2018** [comment]
Can you reproduce the following commands and see what result you get? Change host/port to match the ones on your machine if necessary.
```
curl localhost:9308/cli -d 'drop table if exists test'

curl localhost:9308/cli -d 'create table test(title text)'

curl -X POST http://localhost:9308/bulk -H "Content-Type: application/x-ndjson" -d '
{"insert":{"index":"test","id":1,"doc":{"title":"bulk doc one"}}}
{"insert":{"index":"test","id":2,"doc":{"title":"bulk doc two"}}}
'
```

**Comment by LPeng111** [comment]
It worked.
![image](https://github.com/user-attachments/assets/9e3739a2-4262-4e74-8485-091279df935a)

**Comment by Nick-S-2018** [comment]
So, can you find out the difference between this request and the HTTP request you tried before?

**Comment by LPeng111** [comment]
Yeah, I see.
The `bid_data_test` is in cluster, after I added the `cluster` field, it worked.
Thank you very much.

**Comment by Nick-S-2018** [comment]
That's good to hear.  
I'm closing this issue now. Feel free to reopen it if the error appears again.
