### ISSUE TITLE
Manticoresearch Java Client in Spring Boot 3.0.0

### ISSUE THREAD

**Issue by dipdeepcode** [manticoresoftware/manticoresearch-java#9]
ApiClient client = Configuration.getDefaultApiClient();    
trows Exception     
```    
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration    
at com.manticoresearch.client.Configuration.<clinit>(Configuration.java:13)    
```    
How to fix it?

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
Can you please give us more details on how you've installed the Manticore client and provide some minimal example from your app's code reproducing the issue?

**Comment by dipdeepcode** [comment]
I created a project in intellij idea with spring-boot 3.0.0. 
Added a dependency on manticoresearch:
```
<dependency>
    <groupId>com.manticoresearch</groupId>
    <artifactId>manticoresearch</artifactId>
    <version>3.2.0</version>
</dependency>
```
Added the command 
```
Client Api client = Configuration.getDefaultApiClient();
```
in public static void main().
Running the code
```
mvn clean package spring-boot:run
```
An error occurs when running the code
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
	at com.manticoresearch.client.Configuration.<clinit>(Configuration.java:13)
	at com.example.manticoretest.ManticoreTestApplication.main(ManticoreTestApplication.java:12)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 2 more
```

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
We still cannot reproduce the issue. 
 
Can you provide your full `pom.xml` for us to make a check using your exact configuration?

**Comment by dipdeepcode** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>ru.ddc</groupId>
    <artifactId>manticore-sb3_0_0</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>manticore-sb3.0.0</name>
    <description>manticore-sb3.0.0</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.manticoresearch</groupId>
            <artifactId>manticoresearch</artifactId>
            <version>3.2.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
Thank you, now we've finally managed to reproduce the issue. The problem is related to the Spring Boot version you use (3.0.0).   
Unfortunately, we won't be able to investigate it in the near future so, if this is not crucial for you, we'd suggest you to rollback to a previous version of Spring Boot (e.g., 2.7.5) which should solve the problem.

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
Nick, can you please provide an MRE for the problem, so we can look further into it eventually. Let's also keep this issue open, since eventually I'd like us to make the client compatible with Spring Boot 3

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
Yes, it can be reproduced with the pom file quoted above and the simplest Spring Boot app. 
``` 
import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
 
import com.manticoresearch.client.*; 
 
@SpringBootApplication 
public class App { 
 
    public static void main(String[] args) { 
        ApiClient client = Configuration.getDefaultApiClient();  
    } 
 
} 
 
```

**Comment by vsmid** [comment]
Hi, this is due to the fact that Spring Boot 3 uses Jakarta based libraries. Javax namespace is from the Java EE Oracle era and is a dead technology for a couple of years now. Manticore Java client needs to upgrade its dependencies which use javax namespace to the fresh ones using jakarta namespace. This one would be a valuable upgrade for you guys. People who are evaluating Manticore for usage would certainly be looking at this one as a big blocker.

**Comment by vsmid** [comment]
> ApiClient client = Configuration.getDefaultApiClient(); trows Exception
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration    
> at com.manticoresearch.client.Configuration.<clinit>(Configuration.java:13)    
> ```
> 
> How to fix it?

You could try [migration tool](https://github.com/apache/tomcat-jakartaee-migration).
Internally, It rewrites javax namespaces to jakarta ones. It feels like a hack but it is an option until dependencies get updated. Also, it is an official tool for jakarta migration so why not :)

Another option could also be adding missing dependencies(api and impl.) to you project but I haven't  tried it.

**Comment by sanikolaev** [comment]
Thank you for the info @vsmid . We'll give it a shot.

**Comment by vsmid** [comment]
I took a quick look, you need to replace **jersey** libraries and also **javax annotation**. Others I didn't look right now.
Interesting though, internally there is jakarta.ws.rs 2.1.6 dependendy (via jersey-client-2.35) and you would expect this to be a jakarta namespace but it isn't. This one is causing problems to @DipDeepCode .

**Comment by vsmid** [comment]
Also, I tried migration tool and it didn't work.

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
@vsmid Thank you for your help! It looks like the OpenAPI Generator tool we use to autogenerate the clients has a newer version for Java which supports jersey3 library. So we should be able to solve the issue by upgrading OpenAPI templates and using the new version of the generator.

**Comment by Lamarcke** [comment]
I'm also facing the same issue. Same spring version:
```
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
        at com.manticoresearch.client.Configuration.<clinit>(Configuration.java:13) ~[manticoresearch-3.2.0.jar:na]
        at bibliomar.bibliomarserver.utils.ManticoreUtils.buildSearchClient(ManticoreUtils.java:22) ~[classes/:na]
        at bibliomar.bibliomarserver.utils.ManticoreUtils.getSearchApi(ManticoreUtils.java:31) ~[classes/:na]
        at bibliomar.bibliomarserver.service.search.SearchService.buildSearchApi(SearchService.java:26) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:424) ~[spring-beans-6.0.3.jar:6.0.3]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:368) ~[spring-beans-6.0.3.jar:6.0.3]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:192) ~[spring-beans-6.0.3.jar:6.0.3]
        ... 37 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
        ... 48 common frames omitted
```

Is there any way to use the project with the current spring boot version? Does using the method without dependency injection on the class solves it?

EDIT: I've done some tests and it seems like it doesn't.

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
Done in https://github.com/manticoresoftware/manticoresearch-java/commit/e288ae91396ce3a27ddcea45d5fb005ea7e26991
